# Generated by Django 4.2.1 on 2023-05-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='metaquotes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
