# Generated by Django 4.2.1 on 2023-05-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='backtest1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='backtest2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='backtest3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
