# Generated by Django 4.2.1 on 2023-05-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_price_product_pricebasic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inputs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
