# Generated by Django 4.2.1 on 2023-05-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_product_inputs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inputs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
