# Generated by Django 4.2.1 on 2023-06-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
