# Generated by Django 4.2.1 on 2023-06-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_order_payment_amount_order_plan_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_amount',
        ),
    ]
